//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DK_WEIGHT.AutoWeight.WebReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebReference.DBServiceSoap")]
    public interface DBServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetQuery(string SqlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQueryDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetQueryDataSet(string SqlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQueryDataSetSP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetQueryDataSetSP(string sp_name, string parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQueryJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetQueryJSON(string SqlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SetQuery([System.ServiceModel.MessageParameterAttribute(Name="SetQuery")] string SetQuery1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetQuerySP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SetQuerySP(string sp_name, string parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetQuerySPR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SetQuerySPR(string sp_name, string parameters);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DBServiceSoapChannel : DK_WEIGHT.AutoWeight.WebReference.DBServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBServiceSoapClient : System.ServiceModel.ClientBase<DK_WEIGHT.AutoWeight.WebReference.DBServiceSoap>, DK_WEIGHT.AutoWeight.WebReference.DBServiceSoap {
        
        public DBServiceSoapClient() {
        }
        
        public DBServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetQuery(string SqlString) {
            return base.Channel.GetQuery(SqlString);
        }
        
        public System.Data.DataSet GetQueryDataSet(string SqlString) {
            return base.Channel.GetQueryDataSet(SqlString);
        }
        
        public System.Data.DataSet GetQueryDataSetSP(string sp_name, string parameters) {
            return base.Channel.GetQueryDataSetSP(sp_name, parameters);
        }
        
        public string GetQueryJSON(string SqlString) {
            return base.Channel.GetQueryJSON(SqlString);
        }
        
        public bool SetQuery(string SetQuery1) {
            return base.Channel.SetQuery(SetQuery1);
        }
        
        public bool SetQuerySP(string sp_name, string parameters) {
            return base.Channel.SetQuerySP(sp_name, parameters);
        }
        
        public string SetQuerySPR(string sp_name, string parameters) {
            return base.Channel.SetQuerySPR(sp_name, parameters);
        }
    }
}
